package:
  name: mako
  version: 0.8.1

source:
  fn: Mako-0.8.1.tar.gz
  url: https://pypi.python.org/packages/source/M/Mako/Mako-0.8.1.tar.gz
  md5: 96d962464ce6316004af0cc48495d73e

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1
build:
  number: 0

requirements:
  build:
    - python
    - distribute
    - markupsafe
  run:
    - python

test:
  # Python imports
  imports:
    - mako

about:
  home: https://pypi.python.org/pypi/Mako
  license: MIT License
