package:
  name: mako
  version: 0.9.0

source:
  fn: Mako-0.9.0.tar.gz
  url: https://pypi.python.org/packages/source/M/Mako/Mako-0.9.0.tar.gz
  md5: e2627ba5c65f83dfe39d9a0892ae517d

build:
  number: 0

requirements:
  build:
    - python
    - distribute
    - markupsafe
  run:
    - python

test:
  # Python imports
  imports:
    - mako

about:
  home: https://pypi.python.org/pypi/Mako
  license: MIT License
