package:
  name: wtforms
  version: 1.0.5

source:
  fn: WTForms-1.0.5.zip
  url: https://pypi.python.org/packages/source/W/WTForms/WTForms-1.0.5.zip
  md5: a7ba0af8ed65267e5b421d34940d0151

build:
  number: 0

requirements:
  build:
    - python
    - distribute [py3k]

  run:
    - python

test:
  # Python imports
  imports:
    - wtforms

about:
  home: http://wtforms.simplecodes.com
  license: BSD License
