package:
  name: pylint
  version: 1.0.0

source:
  fn: pylint-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pylint/pylint-1.0.0.tar.gz
  md5: 082b84db04e92f58bba6331060397b05
  patches:
    - remove_tests.patch
    - py3.patch [py3k]

build:
  number: 0
  entry_points:
    - pylint = pylint:run_pylint
    - pylint-gui = pylint:run_pylint_gui
    - epylint = pylint:run_epylint
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar

requirements:
  build:
    - python
  run:
    - python
    - logilab-common
    - astroid

test:
  imports:
    - pylint
  run:
    - pylint --help

about:
  home: http://www.pylint.org
  license: GPL
