package:
  name: nikola
  version: 6.1.1

source:
  fn: nikola-6.1.1.tar.gz
  url: https://pypi.python.org/packages/source/N/Nikola/nikola-6.1.1.tar.gz
  md5: 11ce4cb0223d06fb9df03ff4128bc627

build:
  number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - doit
    - docutils
    - mako
    - pillow
    - pygments
    - unidecode
    - lxml
    - yapsy
    - pyrss2gen
    - pytz
    - logbook
    - configparser [py27]

test:
  imports:
    - nikola

about:
  home: http://nikola.ralsina.com.ar
  license: MIT License
