package:
  name: nikola
  version: 6.0.3

source:
  fn: nikola-6.0.3.zip
  url: https://github.com/getnikola/nikola/archive/nikola-6.0.3.zip
  md5: afcfa9a2adcfecbf4f972980e3e06a45

build:
  number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - doit
    - docutils
    - mako
    - pillow
    - pygments
    - unidecode
    - lxml
    - yapsy
    - pyrss2gen
    - pytz
    - configparser [py27]

test:
  imports:
    - nikola

about:
  home: http://nikola.ralsina.com.ar
  license: MIT License
