package:
  name: pysmb
  version: 1.1.5

source:
  fn: pysmb-1.1.5.tar.gz
  url: https://pypi.python.org/packages/source/p/pysmb/pysmb-1.1.5.tar.gz
  md5: fa6a37830cc7bbe8bae1639da3774496

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - pyasn1

test:
  # Python imports
  imports:
    - smb

about:
  home: https://pypi.python.org/pypi/pysmb
  license: zlib/libpng
