package:
  name: ipython
  version: 1.0.0

source:
  fn: ipython-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/i/ipython/ipython-1.0.0.tar.gz
  md5: 2268fa83f257d14943eb04e3333a6fac


build:
  entry_points:
    - ipython = IPython:start_ipython
    - pycolor = IPython.utils.PyColorize:main
    - ipcontroller = IPython.parallel.apps.ipcontrollerapp:launch_new_instance
    - ipengine = IPython.parallel.apps.ipengineapp:launch_new_instance
    - iplogger = IPython.parallel.apps.iploggerapp:launch_new_instance
    - ipcluster = IPython.parallel.apps.ipclusterapp:launch_new_instance
    - iptest = IPython.testing.iptest:main
    - irunner = IPython.lib.irunner:main [unix]
  number: 0

requirements:
  build:
    - python
    - distribute [win or py3k]
    - pyreadline [win]

  run:
    - python
    - pyreadline [win]
    - pyzmq
    - nose

test:
  imports:
    - IPython

  commands:
    - ipython --help
    - pycolor --help
    - ipcontroller --help
    - ipengine --help
    - iplogger --help
    - ipcluster --help
    - iptest --help
    - irunner --help [unix]

about:
  home: http://ipython.org
  license: BSD License
