package:
  name: tea
  version: 0.0.4

source:
  fn: tea-0.0.4.tar.gz
  url: https://pypi.python.org/packages/source/t/tea/tea-0.0.4.tar.gz
  md5: e86cc41ab2a33f8d9d0c990282dd2378

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - pywin32 [win]
    - psutil  [win]

test:
  # Python imports
  imports:
    - tea

  commands:
    - nosetests tea

  requires:
    - nose
    - pyyaml

about:
  home: https://bitbucket.org/alefnula/tea
  license: BSD License
