package:
  name: tea
  version: 0.0.3

source:
  fn: tea-0.0.3.tar.gz
  url: https://pypi.python.org/packages/source/t/tea/tea-0.0.3.tar.gz
  md5: 1f0828e653845c44740d710280214725

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - pywin32 [win]
    - psutil  [win]

test:
  # Python imports
  imports:
    - tea

  commands:
    - nosetests tea

  requires:
    - nose

about:
  home: https://bitbucket.org/alefnula/tea
  license: BSD License
