package:
  name: markupsafe
  version: 0.18.0

source:
  fn: MarkupSafe-0.18.tar.gz
  url: https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.18.tar.gz
  md5: f8d252fd05371e51dec2fe9a36890687

build:
  number: 0

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  # Python imports
  imports:
    - markupsafe

about:
  home: https://pypi.python.org/pypi/MarkupSafe
  license: BSD License
