package:
  name: pymongo
  version: !!str 2.6.3

source:
  fn: pymongo-2.6.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pymongo/pymongo-2.6.3.tar.gz
  md5: da4a7d6ee47fe30b3978b8805d266167
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pymongo = pymongo:main
    #
    # Would create an entry point called pymongo that calls pymongo.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - distribute

test:
  # Python imports
  imports:
    - bson
    - pymongo
    - gridfs

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/mongodb/mongo-python-driver
  license: ache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
