package:
  name: mercurial
  version: 2.7.0

source:
  fn: mercurial-2.7.tar.gz
  url: https://pypi.python.org/packages/source/M/Mercurial/mercurial-2.7.tar.gz
  md5: 61093c08ca5d8d1310382d17764f0c43

build:
  number: 0

requirements:
  build:
    - python
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    # - distribute

  run:
    - python

test:
  # Python imports
  imports:
    - mercurial

  commands:
    - hg help

about:
  home: http://mercurial.selenic.com/
  license: GNU General Public License (GPL)
