package:
  name: logilab-astng
  version: 0.24.3

source:
  fn: logilab-astng-0.24.3.tar.gz
  url: https://pypi.python.org/packages/source/l/logilab-astng/logilab-astng-0.24.3.tar.gz
  md5: f0dd5dee1d5053939da174e1bfe69388

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - logilab-common

test:
  imports:
    - logilab.astng

about:
  home: http://www.logilab.org/project/logilab-astng
  license: LGPL
