package:
  name: pyasn1
  version: 0.1.7

source:
  fn: pyasn1-0.1.7.tar.gz
  url: https://pypi.python.org/packages/source/p/pyasn1/pyasn1-0.1.7.tar.gz
  md5: 2cbd80fcd4c7b1c82180d3d76fee18c8

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - pyasn1

about:
  home: http://pyasn1.sourceforge.net
  license: BSD License
