package:
  name: doit
  version: 0.23.0

source:
  fn: doit-0.22.1.tar.gz
  url: https://pypi.python.org/packages/source/d/doit/doit-0.23.0.tar.gz
  md5: ac0427ac29cf0e3a22fa9c3089f16dea

build:
  number: 2

requirements:
  build:
    - python

  run:
    - python
    - six

test:
  imports:
    - doit

about:
  home: http://pydoit.org
  license: MIT License
