package:
  name: paramiko
  version: 1.11.0

source:
  fn: paramiko-1.11.0.tar.gz
  url: https://pypi.python.org/packages/source/p/paramiko/paramiko-1.11.0.tar.gz
  md5: a2c55dc04904bd08d984533703177084

build:
  number: 0
  
requirements:
  build:
    - python

  run:
    - python
    - pycrypto

test:
  imports:
    - paramiko

about:
  home: https://github.com/paramiko/paramiko/
  license: GNU Library or Lesser General Public License (LGPL)
