package:
  name: sphinxcontrib-napoleon
  version: !!str 0.2.2

source:
  fn: sphinxcontrib-napoleon-0.2.2.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinxcontrib-napoleon/sphinxcontrib-napoleon-0.2.2.tar.gz
  md5: e67d0f3b7b87adc436ecd6e45b825cda

build:
  number: 0

requirements:
  build:
    - python
    - distribute
    - sphinx

  run:
    - python
    - distribute
    - sphinx

test:
  # Python imports
  imports:
    - sphinxcontrib.napoleon
    - tests
    - tests.napoleon
    - sphinxcontrib

about:
  home: https://bitbucket.org/birkenfeld/sphinx-contrib
  license: BSD License
