package:
  name: phonenumbers
  version: !!str 5.9.2

source:
  fn: phonenumbers-5.9.2.tar.gz
  url: https://pypi.python.org/packages/source/p/phonenumbers/phonenumbers-5.9.2.tar.gz
  md5: 8272ffdcec4537e58807a6dd3d4a60cd
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - phonenumbers = phonenumbers:main
    #
    # Would create an entry point called phonenumbers that calls phonenumbers.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - distribute

test:
  # Python imports
  imports:
    - phonenumbers
    - phonenumbers.geodata
    - phonenumbers.carrierdata
    - phonenumbers.shortdata
    - phonenumbers.data
    - phonenumbers.tzdata

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/daviddrysdale/python-phonenumbers
  license: ache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
