package:
  name: django
  version: 1.5.1

source:
  fn: Django-1.5.1.tar.gz
  url: https://pypi.python.org/packages/source/D/Django/Django-1.5.1.tar.gz
  md5: 7465f6383264ba167a9a031d6b058bff

build:
  number: 0
  entry_points:
    - django-admin = django.core.management:execute_from_command_line

requirements:
  build:
    - python
  run:
    - python

test:
  # Python imports
  imports:
    - django

  commands:
    - django-admin --help

about:
  home: http://www.djangoproject.com
  license: BSD License
