package:
  name: django
  version: 1.6

source:
  fn: Django-1.6.tar.gz
  url: https://pypi.python.org/packages/source/D/Django/Django-1.6.tar.gz
  md5: 65db1bc313124c3754c89073942e38a8

build:
  number: 0
  entry_points:
    - django-admin = django.core.management:execute_from_command_line

requirements:
  build:
    - python
  run:
    - python

test:
  # Python imports
  imports:
    - django

  commands:
    - django-admin --help

about:
  home: http://www.djangoproject.com
  license: BSD License
