package:
  name: pytz
  version: 2013b

source:
  fn: pytz-2013b.tar.gz
  url: https://pypi.python.org/packages/source/p/pytz/pytz-2013b.tar.gz
  md5: 64dd31f3f731a5adf9754c32e00d46c3

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - pytz

about:
  home: http://pytz.sourceforge.net
  license: MIT License
