package:
  name: south
  version: 0.8.4

source:
  fn: South-0.8.4.tar.gz
  url: https://pypi.python.org/packages/source/S/South/South-0.8.4.tar.gz
  md5: ccd6ebadd3e2c8c6ef16d771632f7840

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - django

test:
  # Python imports
  imports:
    - south

about:
  home: http://south.aeracode.org/
  license: ache Software License
