package:
  name: pelican
  version: 3.3

source:
  fn: pelican-3.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pelican/pelican-3.3.tar.gz
  md5: 0e1c16a13290e19e02b739ad7a9b3850

build:
  entry_points:
    - pelican = pelican:main
    - pelican-import = pelican.tools.pelican_import:main
    - pelican-quickstart = pelican.tools.pelican_quickstart:main
    - pelican-themes = pelican.tools.pelican_themes:main

  number: 0

requirements:
  build:
    - python
    - distribute
    - feedgenerator
    - jinja2
    - pygments
    - docutils
    - pytz
    - blinker
    - unidecode
    - six
    - markupsafe
    - markdown
    - typogrify

  run:
    - python
    - feedgenerator
    - jinja2
    - pygments
    - docutils
    - pytz
    - blinker
    - unidecode
    - six
    - markupsafe
    - markdown
    - typogrify

test:
  imports:
    - pelican

  commands:
    - pelican --help
    - pelican-import --help
    - pelican-quickstart --help
    - pelican-themes --help

about:
  home: http://getpelican.com/
  license: GNU Affero General Public License v3
