package:
  name: blinker
  version: 1.3

source:
  fn: blinker-1.3.tar.gz
  url: https://pypi.python.org/packages/source/b/blinker/blinker-1.3.tar.gz
  md5: 66e9688f2d287593a0e698cd8a5fbc57

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - blinker

about:
  home: http://pythonhosted.org/blinker/
  license: MIT License
