package:
  name: yapsy
  version: 1.10.2

source:
  fn: Yapsy-1.10.2-pythons2n3.tar.gz
  url: https://pypi.python.org/packages/source/Y/Yapsy/Yapsy-1.10.2-pythons2n3.tar.gz
  md5: d905b574d4f55ff62e02603ec3dc89b3

build:
  number: 0

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  imports:
    - yapsy

about:
  home: http://yapsy.sourceforge.net
  license: BSD License
