package:
  name: alembic
  version: 0.6.0

source:
  fn: alembic-0.6.0.tar.gz
  url: https://pypi.python.org/packages/source/a/alembic/alembic-0.6.0.tar.gz
  md5: 084fe81b48ebae43b0f6031af68a03d6

build:
  number: 0
  entry_points:
    - alembic = alembic.config:main

requirements:
  build:
    - python
    - distribute
    - mako
    - sqlalchemy
  run:
    - python
    - mako
    - sqlalchemy

test:
  # Python imports
  imports:
    - alembic

about:
  home: https://pypi.python.org/pypi/alembic
  license: MIT License
